# Generated by Django 5.0.7 on 2026-07-30 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('unitType', models.CharField(choices=[('DIRECTORATE', 'Directorate'), ('DEPARTMENT', 'Department'), ('UNIT', 'Unit'), ('SECTION', 'Section')], max_length=20)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.organisationalunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationalUnitHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(db_index=True, max_length=50)),
                ('leadershipRole', models.CharField(choices=[('HEAD_OF_DIRECTORATE', 'Head of Directorate'), ('HEAD_OF_DEPARTMENT', 'Head of Department'), ('HEAD_OF_UNIT', 'Head of Unit'), ('HEAD_OF_SECTION', 'Head of Section')], max_length=30)),
                ('isActing', models.BooleanField(default=False)),
                ('effectiveFrom', models.DateField()),
                ('effectiveTo', models.DateField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('organisationalUnit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='organization.organisationalunit')),
            ],
            options={
                'ordering': ['-effectiveFrom'],
            },
        ),
    ]
