# Generated by Django 5.0.7 on 2026-07-20 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_userprofile_tokensinvalidbefore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fileName', models.CharField(blank=True, max_length=255)),
                ('createdBy', models.CharField(blank=True, max_length=120)),
                ('totalRows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowNumber', models.PositiveIntegerField()),
                ('checkNumber', models.CharField(blank=True, max_length=50)),
                ('personnelNumber', models.CharField(blank=True, max_length=50)),
                ('firstName', models.CharField(blank=True, max_length=150)),
                ('lastName', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('departmentId', models.CharField(blank=True, max_length=50)),
                ('designationId', models.IntegerField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('errorMessage', models.TextField(blank=True)),
                ('emailSent', models.BooleanField(default=False)),
                ('createdUserId', models.CharField(blank=True, max_length=50)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='identity.employeeimportbatch')),
            ],
            options={
                'ordering': ['rowNumber'],
            },
        ),
    ]
