# Generated by Django 5.0.7 on 2026-07-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_employeeimportbatch_employeeimportrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organisationalUnitId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
